#!/bin/bash
#
# generate_hash_vectors.sh
#
# Generates deterministic hash test vectors using the native build.
# These vectors are used to verify cross-platform hash consistency.
#
# Usage:
#   ./scripts/generate_hash_vectors.sh
#
# Output:
#   Prints Rust test vector definitions that can be pasted into tests/cross_platform_tests.rs
#   Also outputs JSON format for snapshot files
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}=== Deterministic Hash Vector Generator ===${NC}"
echo ""

if [ ! -f "$PROJECT_ROOT/Cargo.toml" ]; then
    echo -e "${RED}Error: Cargo.toml not found. Are you in the project root?${NC}"
    exit 1
fi

# Function to generate vectors using openssl
generate_vectors_with_openssl() {
    local vectors=(
        "minimal_payload:0000000000000000000000000000000000000000000000000000000000000000:1700000000:kyc_approved"
        "longer_payload:0000000000000000000000000000000000000000000000000000000000000001:1700000001:payment_confirmed_with_extended_metadata"
        "zero_timestamp:0000000000000000000000000000000000000000000000000000000000000002:0:genesis_attestation"
        "max_timestamp:0000000000000000000000000000000000000000000000000000000000000003:18446744073709551615:future_attestation"
        "empty_payload:0000000000000000000000000000000000000000000000000000000000000004:1600000000:"
    )

    if ! command -v openssl &> /dev/null; then
        echo -e "${RED}Error: openssl not found${NC}"
        exit 1
    fi

    echo "// Hardcoded test vectors for cross-platform hash verification"
    echo "// Generated by: scripts/generate_hash_vectors.sh"
    echo "// Reference platform: native"
    echo ""

    for vector in "${vectors[@]}"; do
        IFS=':' read -r name subject_xdr timestamp data <<< "$vector"
        
        local input_hex="$subject_xdr"
        
        printf -v ts_be '%016x' "$timestamp"
        input_hex="${input_hex}${ts_be}"
        
        if [ -n "$data" ]; then
            input_hex="${input_hex}$(echo -n "$data" | xxd -p)"
        fi
        
        local hash=$(echo -n "$input_hex" | xxd -r -p | openssl dgst -sha256 -hex | awk '{print $2}')
        
        echo "pub const VECTOR_${name^^}: HashTestVector = HashTestVector {"
        echo "    name: \"$name\","
        echo "    subject_xdr_hex: \"$subject_xdr\","
        echo "    timestamp: ${timestamp}u64,"
        echo "    data_payload: b\"$data\","
        echo "    expected_hash: \"$hash\","
        echo "};"
        echo ""
    done
}

# Use openssl to generate vectors (reliable and avoids rustc dependency resolution issues)
echo -e "${YELLOW}Using openssl for hash computation...${NC}"
generate_vectors_with_openssl

echo ""
echo -e "${GREEN}Vector generation complete!${NC}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "1. Copy the Rust constants above into tests/cross_platform_tests.rs"
echo "2. Update test_snapshots/deterministic_hash_tests/test_cross_environment_determinism.1.json"
echo "3. Run: cargo test --test cross_platform_tests"
echo "4. Verify tests pass on both native and WASM targets"
